<<<<<<< HEAD
---
- name: Download Helm tarball
  ansible.builtin.get_url:
    url: "{{ helm_download_url }}"
    dest: "/tmp/helm-{{ helm_version }}-{{ helm_platform }}.tar.gz"

- name: Extract Helm tarball
  ansible.builtin.unarchive:
    src: "/tmp/helm-{{ helm_version }}-{{ helm_platform }}.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Move Helm binary to /usr/local/bin
  ansible.builtin.command: mv /tmp/{{ helm_platform }}/helm "{{ helm_bin_path }}"
  args:
    creates: "{{ helm_bin_path }}"

- name: Ensure Helm binary is executable
  ansible.builtin.file:
    path: "{{ helm_bin_path }}"
    mode: '0755'
    state: file

- name: Clean up tarball
  ansible.builtin.file:
    path: "/tmp/helm-{{ helm_version }}-{{ helm_platform }}.tar.gz"
    state: absent

- name: Clean up extracted directory
  ansible.builtin.file:
    path: "/tmp/{{ helm_platform }}"
    state: absent

- name: Check Helm version
  ansible.builtin.command: "{{ helm_bin_path }} version"
  register: helm_version_output

- name: Display Helm version
  ansible.builtin.debug:
    msg: "{{ helm_version_output.stdout }}"
=======
---
- name: Download Helm tarball
  ansible.builtin.get_url:
    url: "{{ helm_download_url }}"
    dest: "/tmp/helm-{{ helm_version }}-{{ helm_platform }}.tar.gz"

- name: Extract Helm tarball
  ansible.builtin.unarchive:
    src: "/tmp/helm-{{ helm_version }}-{{ helm_platform }}.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Move Helm binary to /usr/local/bin
  ansible.builtin.command: mv /tmp/{{ helm_platform }}/helm "{{ helm_bin_path }}"
  args:
    creates: "{{ helm_bin_path }}"

- name: Ensure Helm binary is executable
  ansible.builtin.file:
    path: "{{ helm_bin_path }}"
    mode: '0755'
    state: file

- name: Clean up tarball
  ansible.builtin.file:
    path: "/tmp/helm-{{ helm_version }}-{{ helm_platform }}.tar.gz"
    state: absent

- name: Clean up extracted directory
  ansible.builtin.file:
    path: "/tmp/{{ helm_platform }}"
    state: absent

- name: Check Helm version
  ansible.builtin.command: "{{ helm_bin_path }} version"
  register: helm_version_output

- name: Display Helm version
  ansible.builtin.debug:
    msg: "{{ helm_version_output.stdout }}"
>>>>>>> 8268c6b (added files)
