---
- name: Ensure that git is installed
  ansible.builtin.package:
    name: git
    state: present
  become: true

- name: Ensure that kubectl is installed
  command: "which kubectl"
  register: kubectl_check
  changed_when: False
  failed_when: kubectl_check.rc != 0

- name: Clone the AWS Cloud Controller Manager repository
  ansible.builtin.git:
    repo: https://github.com/kubernetes/cloud-provider-aws.git
    dest: /tmp/cloud-provider-aws
    version: master
    force: yes

- name: Delete existing AWS Cloud Controller Manager manifests if present
  command: "kubectl delete -k ."
  args:
    chdir: /tmp/cloud-provider-aws/examples/existing-cluster/base
  ignore_errors: true  # Ignore errors if no resources are found
  environment:
    KUBECONFIG: "/home/ansible-user/.kube/config"  # Set KUBECONFIG to the correct path

- name: Apply AWS Cloud Controller Manager manifests
  ansible.builtin.command:
    cmd: "kubectl create -k . --validate=false"  # Added --validate=false to bypass validation errors
  args:
    chdir: /tmp/cloud-provider-aws/examples/existing-cluster/base
  environment:
    KUBECONFIG: "/home/ansible-user/.kube/config"  # Set KUBECONFIG to the correct path

- name: Check if AWS Cloud Controller Manager pods are running
  command: "kubectl get pods -n kube-system -l app=aws-cloud-controller-manager"
  register: ccm_check
  until: ccm_check.rc == 0
  retries: 2
  delay: 30
  environment:
    KUBECONFIG: "/home/ansible-user/.kube/config"  # Set KUBECONFIG to the correct path

- name: Debug Cloud Controller Manager installation result
  ansible.builtin.debug:
    var: ccm_check  # Updated to use the correct variable for pod check
