- name: Update apt repositories
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Create containerd modules-load configuration
  copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter

- name: Load overlay module
  modprobe:
    name: overlay
    state: present

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Set sysctl parameters for Kubernetes
  copy:
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply sysctl parameters
  command: sysctl --system

- name: Install containerd
  apt:
    name: containerd
    state: present

- name: Ensure containerd configuration directory exists
  file:
    path: /etc/containerd
    state: directory

- name: Create containerd default config file
  command: containerd config default > /tmp/containerd_config.toml
  changed_when: false

- name: Set Cgroup driver as Systemd
  lineinfile:
    insertafter: '.*\[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options\]$'
    line: "SystemdCgroup = true"
    path: /tmp/containerd_config.toml
  become: yes

- name: Remove SystemdCgroup = false
  lineinfile:
    path: /tmp/containerd_config.toml
    line: "SystemdCgroup = false"
    state: absent
  notify: restart containerd
  become: yes

- name: Copy containerd config to /etc/containerd/config.toml
  copy:
    src: /tmp/containerd_config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Validate containerd configuration
  shell: containerd config dump | tee /dev/null
  register: validate_output
  failed_when: validate_output.rc != 0
  become: yes

- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted
    enabled: yes
