---
- name: Apply label to all Kubernetes nodes
  hosts: master1,master2,master3
  gather_facts: false

  tasks:
    - name: Label each node with the master role
      command: kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/master=true --overwrite

    - name: Display verification output
      shell: kubectl get nodes --show-labels
      register: verify_output
      changed_when: false

    - name: Show labeled nodes
      debug:
        var: verify_output.stdout_lines
