---
- name: Configure master2 and master3 nodes for Kubernetes
  hosts: master2, master3
  become: yes
  tasks:
    - name: Ensure KUBECONFIG path is set globally
      lineinfile:
        path: /etc/profile
        line: "export KUBECONFIG=/etc/kubernetes/admin.conf"
        state: present

    - name: Source /etc/profile to load KUBECONFIG globally
      shell: |
        source /etc/profile
      args:
        executable: /bin/bash

    - name: Verify KUBECONFIG path
      shell: |
        source /etc/profile
        echo $KUBECONFIG
      args:
        executable: /bin/bash
      register: kubectl_env
      failed_when: "'/etc/kubernetes/admin.conf' not in kubectl_env.stdout"

    - name: Debug KUBECONFIG path verification output
      debug:
        var: kubectl_env.stdout

    - name: Ensure kube-controller-manager and kube-scheduler have correct configuration
      shell: |
        sed -i '/--leader-elect/ s|$| --kubeconfig=/etc/kubernetes/controller-manager.conf|' /etc/kubernetes/manifests/kube-controller-manager.yaml
        sed -i '/--leader-elect/ s|$| --kubeconfig=/etc/kubernetes/scheduler.conf|' /etc/kubernetes/manifests/kube-scheduler.yaml
      args:
        executable: /bin/bash

    - name: Restart kubelet service
      service:
        name: kubelet
        state: restarted

    - name: Wait for kubelet service to stabilize
      wait_for:
        path: /var/lib/kubelet/kubeadm-flags.env
        timeout: 30

    - name: Check kube-apiserver logs
      shell: |
        kubectl logs -n kube-system kube-apiserver-{{ inventory_hostname }}
      args:
        executable: /bin/bash
      register: apiserver_logs

    - name: Debug kube-apiserver logs
      debug:
        var: apiserver_logs.stdout
