<<<<<<< HEAD
---
- name: Init master1
  hosts: master1
  become: yes
  tasks:
    - name: Initalsize first master1
      import_role:
        name: first-master
=======
---
- name: Init master1
  hosts: master1
  become: yes
  tasks:
    - name: Initalsize first master1
      import_role:
        name: first-master
>>>>>>> 8268c6b (added files)
