- name: Generate Join command for new masters
  hosts: master1
  become: yes
  tasks:
    - name: Generate Join command
      command: kubeadm token create --print-join-command
      register: join_command
      environment:  # Corrected spelling here
        KUBECONFIG: /home/ansible-user/.kube/config  # Removed extra space in path
      changed_when: false

    - name: Set join command as fact
      set_fact:
        kubeadm_join_command: "{{ join_command.stdout }}"

- name: Add new masters to cluster
  hosts: master2, master3
  become: yes
  tasks:
    - name: Join Master 2 and Master 3 to cluster
      command: "{{ hostvars['master1']['kubeadm_join_command'] }}"
      environment:  # Corrected spelling here
        KUBECONFIG: /home/ansible-user/.kube/config  # Removed extra space in path
