
- name: Generate Join command for new masters
  hosts: master1
  become: yes
  tasks:
    - name: Generate Join command
      command: kubeadm token create --print-join-command
      register: join_command
      enviroment:
        KUBECONFIG: / home/ansible-user/.kube/config
      changed_when: false

    - name: Set join comand as fact
      set_fact:
        kubeadm_join_command: "{{ join_command.stdout}}"

- name: Add new masters to cluster
  hosts: master2, master3
  become: yes
  tasks:
    - name: Join Master 2 and Master3 to cluster
      command: "{{ hostvars['master1']['kubeadm_join_command']}}"
      enviroment:
        KUBECONFIG: / home/ansible-user/.kube/config

