<<<<<<< HEAD
---
- name: Prepare Nodes for Running Kubernetes
  hosts: k8s_node
  become: yes
  tasks:
    - name: Import K8s-setup role
      import_role:
        name: k8s-setup
=======
---
- name: Prepare Nodes for Running Kubernetes
  hosts: k8s_node
  become: yes
  tasks:
    - name: Import K8s-setup role
      import_role:
        name: k8s-setup
>>>>>>> 8268c6b (added files)
