---
- name: Copy Kubernetes manifest files and admin.conf from master1 to other masters
  hosts: master2,master3
  become: yes
  tasks:
    - name: Fetch manifest files from master1 to the controller
      fetch:
        src: "/etc/kubernetes/manifests/{{ item }}"
        dest: "/tmp/manifests/{{ item }}"
        flat: yes
        validate_checksum: no
      delegate_to: master1
      with_items:
        - etcd.yaml
        - kube-apiserver.yaml
        - kube-controller-manager.yaml
        - kube-scheduler.yaml

    - name: Copy fetched manifest files to remote masters
      copy:
        src: "/tmp/manifests/{{ item }}"
        dest: "/etc/kubernetes/manifests/{{ item }}"
        owner: root
        group: root
        mode: '0644'
        remote_src: no
      with_items:
        - etcd.yaml
        - kube-apiserver.yaml
        - kube-controller-manager.yaml
        - kube-scheduler.yaml

    - name: Fetch admin.conf from master1 to the controller
      fetch:
        src: "/etc/kubernetes/admin.conf"
        dest: "/tmp/admin.conf"
        flat: yes
        validate_checksum: no
      delegate_to: master1

    - name: Copy admin.conf to the remote masters
      copy:
        src: "/tmp/admin.conf"
        dest: "/etc/kubernetes/admin.conf"
        owner: root
        group: root
        mode: '0600'
        remote_src: no

    - name: Apply the manifest files on remote masters
      shell: |
        export KUBEVERSION=$(kubectl version --short | grep "Server Version" | awk '{print $3}')
        kubectl apply -f /etc/kubernetes/manifests/{{ item }}
      with_items:
        - etcd.yaml
        - kube-apiserver.yaml
        - kube-controller-manager.yaml
        - kube-scheduler.yaml
