<<<<<<< HEAD
---
- name: synchronize time on all servers
  hosts: k8s_node
  become: yes
  tasks:
    - name: Sync time across all nodes
      import_role:
        name: time-sync
=======
---
- name: synchronize time on all servers
  hosts: k8s_node
  become: yes
  tasks:
    - name: Sync time across all nodes
      import_role:
        name: time-sync
>>>>>>> 8268c6b (added files)
